// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tripdeals/promo.service/src/service (interfaces: StrikeThroughtPriceService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	base "github.com/harryosmar/generic-gorm/base"
	entity "github.com/tripdeals/promo.service/src/entity"
)

// MockStrikeThroughtPriceService is a mock of StrikeThroughtPriceService interface.
type MockStrikeThroughtPriceService struct {
	ctrl     *gomock.Controller
	recorder *MockStrikeThroughtPriceServiceMockRecorder
}

// MockStrikeThroughtPriceServiceMockRecorder is the mock recorder for MockStrikeThroughtPriceService.
type MockStrikeThroughtPriceServiceMockRecorder struct {
	mock *MockStrikeThroughtPriceService
}

// NewMockStrikeThroughtPriceService creates a new mock instance.
func NewMockStrikeThroughtPriceService(ctrl *gomock.Controller) *MockStrikeThroughtPriceService {
	mock := &MockStrikeThroughtPriceService{ctrl: ctrl}
	mock.recorder = &MockStrikeThroughtPriceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrikeThroughtPriceService) EXPECT() *MockStrikeThroughtPriceServiceMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockStrikeThroughtPriceService) Activate(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockStrikeThroughtPriceServiceMockRecorder) Activate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockStrikeThroughtPriceService)(nil).Activate), arg0, arg1)
}

// BySlugs mocks base method.
func (m *MockStrikeThroughtPriceService) BySlugs(arg0 context.Context, arg1 []string) ([]entity.StrikeThroughtPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BySlugs", arg0, arg1)
	ret0, _ := ret[0].([]entity.StrikeThroughtPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BySlugs indicates an expected call of BySlugs.
func (mr *MockStrikeThroughtPriceServiceMockRecorder) BySlugs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BySlugs", reflect.TypeOf((*MockStrikeThroughtPriceService)(nil).BySlugs), arg0, arg1)
}

// Create mocks base method.
func (m *MockStrikeThroughtPriceService) Create(arg0 context.Context, arg1 *entity.StrikeThroughtPrice) (*entity.StrikeThroughtPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*entity.StrikeThroughtPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStrikeThroughtPriceServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStrikeThroughtPriceService)(nil).Create), arg0, arg1)
}

// Deactivate mocks base method.
func (m *MockStrikeThroughtPriceService) Deactivate(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockStrikeThroughtPriceServiceMockRecorder) Deactivate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockStrikeThroughtPriceService)(nil).Deactivate), arg0, arg1)
}

// Detail mocks base method.
func (m *MockStrikeThroughtPriceService) Detail(arg0 context.Context, arg1 int64) (*entity.StrikeThroughtPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", arg0, arg1)
	ret0, _ := ret[0].(*entity.StrikeThroughtPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockStrikeThroughtPriceServiceMockRecorder) Detail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockStrikeThroughtPriceService)(nil).Detail), arg0, arg1)
}

// List mocks base method.
func (m *MockStrikeThroughtPriceService) List(arg0 context.Context, arg1, arg2 int, arg3 []base.OrderBy, arg4 []base.Where) ([]entity.StrikeThroughtPrice, *base.Paginator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]entity.StrikeThroughtPrice)
	ret1, _ := ret[1].(*base.Paginator)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockStrikeThroughtPriceServiceMockRecorder) List(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStrikeThroughtPriceService)(nil).List), arg0, arg1, arg2, arg3, arg4)
}

// Update mocks base method.
func (m *MockStrikeThroughtPriceService) Update(arg0 context.Context, arg1 *entity.StrikeThroughtPrice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStrikeThroughtPriceServiceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStrikeThroughtPriceService)(nil).Update), arg0, arg1)
}
